---
extends: default

ignore-from-file: .gitignore

rules:
  document-start: disable
  line-length:
    ignore: config/credentials/*
    # Ideally, this value would be smaller, but it makes dealing with long lines
    #  including commit SHAs, etc. very difficult.
    max: 120
  truthy:
    ignore: .github/workflows/*
