name: CI

on:
  push:
  workflow_call:

env:
  MISE_ENV: development

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
        with:
          cache: true
      - run: mise actionlint

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0  # Full history is needed to scan all commits
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
        with:
          cache: true
      - run: mise gitleaks

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
        with:
          cache: true
      - env:
          SECRET_KEY: "${{ secrets.SECRET_KEY_FOR_TESTS }}"
        run: mise test

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
        with:
          cache: true
      - run: mise lint

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
        with:
          cache: true
      - run: mise yamllint

  coverage:
    needs: [pytest]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      badge_url: ${{ steps.upload-coverage-badge-artifact-step.outputs.artifact-url }}
      html_report_url: ${{ steps.upload-html-report-artifact-step.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          cache: true
      - env:
          SECRET_KEY: "${{ secrets.SECRET_KEY_FOR_TESTS }}"
          COVERAGE_THRESHOLD: 80
        run: mise test:coverage
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        id: upload-html-report-artifact-step
        if: always()
        with:
          name: coverage-html
          path: htmlcov
          retention-days: 10
          compression-level: 0
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        id: upload-coverage-badge-artifact-step
        if: always()
        with:
          name: coverage-badge
          path: coverage.svg
          retention-days: 10
          compression-level: 0
